In [1]:
import numpy as np


In [2]:
text_path="/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/attentive_cyclegan/data/INIT/label/rainy_train/rainy/rainy2.txt"
a_path=np.loadtxt(text_path,dtype=str, delimiter=' ', skiprows=0, usecols=(0))
print(a_path)

['1.png' '3' '0' '4' '1' '1' '1' '1' '1.png' '3' '0' '12' '1' '1' '2' '2'
 '2' '2' '2' '2' '2' '2' '2' '2' '1.png' '3' '0' '11' '1' '1' '1' '1' '1'
 '1' '2' '2' '2' '2' '2']


In [ ]:
# cls_ = np.loadtxt(text_path, dtype=int, delimiter=' ', skiprows=2, usecols=(0))
# print(cls_)


In [4]:
# text_path = "your_file.txt"

with open(text_path, "r") as file:
    lines = file.readlines()

# Extract cls_ values, skipping non-numeric lines
cls_ = []
for line in lines[2:]:  # Start reading from the 3rd line (zero-based index)
    parts = line.split()
    if parts and parts[0].isdigit():  # Ensure the first element is a number
        cls_.append(int(parts[0]))

print(cls_)


[3, 0, 4, 1, 1, 1, 1, 3, 0, 12, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 0, 11, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]


In [5]:
# box_ = np.loadtxt(text_path, dtype=float, delimiter=' ', skiprows=2, usecols=(1,2,3,4))


In [6]:
import numpy as np

# text_path = "your_file.txt"

# Read all lines
with open(text_path, "r") as file:
    lines = file.readlines()

# Skip non-numeric lines (First two lines contain non-relevant info)
numeric_lines = []
for line in lines[2:]:  # Skip first 2 lines (1.png and metadata)
    parts = line.strip().split()
    
    # Ensure the row has exactly 5 values (class_id + 4 box coordinates)
    if len(parts) == 5 and parts[0].isdigit():
        numeric_lines.append(" ".join(parts))  # Convert back to string

# Convert filtered lines to numpy array
if numeric_lines:
    from io import StringIO
    box_ = np.loadtxt(StringIO("\n".join(numeric_lines)), dtype=float, delimiter=" ", usecols=(1,2,3,4))
    print(box_)
else:
    print("No valid bounding box data found.")


[[2896. 1583. 3114. 1722.]
 [2312. 1514. 2359. 1555.]
 [2171. 1503. 2201. 1534.]
 [2117. 1490. 2146. 1531.]
 [1314. 1420. 1629. 1592.]
 [2072. 1447. 2093. 1469.]
 [2568. 1283. 2609. 1325.]
 [ 167.  631.  247.  755.]
 [ 127.  789.  212.  914.]
 [ 160.  732.  221.  806.]
 [ 127.  902.  179.  944.]
 [ 136.  943.  198. 1022.]
 [  99. 1059.  155. 1204.]
 [ 126. 1015.  193. 1071.]
 [1950. 1362. 1967. 1378.]
 [1951. 1378. 1968. 1395.]
 [ 721. 1350. 1421. 1750.]
 [1627. 1363. 1706. 1435.]
 [1759. 1374. 1784. 1401.]
 [3095. 1274. 3539. 1593.]
 [3026. 1428. 3116. 1523.]
 [2959. 1435. 3006. 1479.]
 [ 481. 1012.  591. 1165.]
 [1364. 1191. 1400. 1228.]
 [1363. 1230. 1398. 1243.]
 [1362. 1244. 1397. 1279.]
 [2610.  816. 2741.  950.]]


In [7]:
# if box_.size == 4:
cls_ = np.expand_dims(cls_, axis=0)
box_ = np.expand_dims(box_, axis=0)
print(cls_)
print(box_)
print(cls_.shape)
print(box_.shape)

    # print(box_)
# mask_ = self.make_mask(cls_, box_)

[[ 3  0  4  1  1  1  1  3  0 12  1  1  2  2  2  2  2  2  2  2  2  2  3  0
  11  1  1  1  1  1  1  2  2  2  2  2]]
[[[2896. 1583. 3114. 1722.]
  [2312. 1514. 2359. 1555.]
  [2171. 1503. 2201. 1534.]
  [2117. 1490. 2146. 1531.]
  [1314. 1420. 1629. 1592.]
  [2072. 1447. 2093. 1469.]
  [2568. 1283. 2609. 1325.]
  [ 167.  631.  247.  755.]
  [ 127.  789.  212.  914.]
  [ 160.  732.  221.  806.]
  [ 127.  902.  179.  944.]
  [ 136.  943.  198. 1022.]
  [  99. 1059.  155. 1204.]
  [ 126. 1015.  193. 1071.]
  [1950. 1362. 1967. 1378.]
  [1951. 1378. 1968. 1395.]
  [ 721. 1350. 1421. 1750.]
  [1627. 1363. 1706. 1435.]
  [1759. 1374. 1784. 1401.]
  [3095. 1274. 3539. 1593.]
  [3026. 1428. 3116. 1523.]
  [2959. 1435. 3006. 1479.]
  [ 481. 1012.  591. 1165.]
  [1364. 1191. 1400. 1228.]
  [1363. 1230. 1398. 1243.]
  [1362. 1244. 1397. 1279.]
  [2610.  816. 2741.  950.]]]
(1, 36)
(1, 27, 4)
