In [17]:
import numpy as np
from PIL import Image


In [29]:
text_path="/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/domain_adaptation/init_original_copy/label/sunny_train/sunny/sunny_1.txt"
a_path=np.loadtxt(text_path,dtype=str, delimiter=' ', skiprows=0, usecols=(0))
print(a_path)
print(a_path[0])

['/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/delhi_airshed/images/8558197_3353442.tif'
 '3' '0' '4' '1']
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/delhi_airshed/images/8558197_3353442.tif


In [30]:
cls_ = np.loadtxt(text_path, dtype=int, delimiter=' ', skiprows=5, usecols=(0))
print(cls_)


1


In [31]:
# # text_path = "your_file.txt"

# with open(text_path, "r") as file:
#     lines = file.readlines()

# # Extract cls_ values, skipping non-numeric lines
# cls_ = []
# for line in lines[2:]:  # Start reading from the 3rd line (zero-based index)
#     parts = line.split()
#     if parts and parts[0].isdigit():  # Ensure the first element is a number
#         cls_.append(int(parts[0]))

# print(cls_)


In [32]:
box_ = np.loadtxt(text_path, dtype=float, delimiter=' ', skiprows=5, usecols=(1,2,3,4))
print(box_)


[2896. 1583. 3114. 1722.]


In [33]:
import numpy as np

# text_path = "your_file.txt"

# Read all lines
with open(text_path, "r") as file:
    lines = file.readlines()

# Skip non-numeric lines (First two lines contain non-relevant info)
numeric_lines = []
for line in lines[2:]:  # Skip first 2 lines (1.png and metadata)
    parts = line.strip().split()
    
    # Ensure the row has exactly 5 values (class_id + 4 box coordinates)
    if len(parts) == 5 and parts[0].isdigit():
        numeric_lines.append(" ".join(parts))  # Convert back to string

# Convert filtered lines to numpy array
if numeric_lines:
    from io import StringIO
    box_ = np.loadtxt(StringIO("\n".join(numeric_lines)), dtype=float, delimiter=" ", usecols=(1,2,3,4))
    print(box_)
else:
    print("No valid bounding box data found.")


[2896. 1583. 3114. 1722.]


In [34]:
# if box_.size == 4:
cls_ = np.expand_dims(cls_, axis=0)
box_ = np.expand_dims(box_, axis=0)
print(cls_)
print(box_)
print(cls_.shape)
print(box_.shape)

    # print(box_)
# mask_ = self.make_mask(cls_, box_)

[1]
[[2896. 1583. 3114. 1722.]]
(1,)
(1, 4)


In [38]:
box_ = np.round(box_ / 4) * 4
print(box_)
box_ = box_.astype('int')
print(box_)

[[2896. 1584. 3112. 1720.]]
[[2896 1584 3112 1720]]


In [39]:
print(box_.shape)
print(box_[:,2])

(1, 4)
[3112]


In [40]:
box_[:,0]

array([2896])

In [37]:
w = box_[:,2] - box_[:,0]
print(w)

[216]


In [18]:
def make_mask(self, cls, box):
    mask1 = Image.new('L', (self.size_w, self.size_h), 0)
    mask2 = Image.new('L', (self.size_w, self.size_h), 0)
    mask3 = Image.new('L', (self.size_w, self.size_h), 0)

    box_ = np.round(box / 4) * 4
    print("box_shape: ", box_.shape)
    box_ = box_.astype('int')

    w = box_[:,2] - box_[:,0]
    print("w shape: ", w.shape)

    h = box_[:,3] - box_[:,1]
    print("h shape: ", h.shape)
    print("clas size: ", cls.size)
    for idx in range(cls.size):
        if cls[idx] == 1:
            sub = Image.new('L', (w[idx], h[idx]), 255)
            mask1.paste(sub, (box_[idx, 0], box_[idx, 1]))
        elif cls[idx] == 2:
            sub = Image.new('L', (w[idx], h[idx]), 255)
            mask2.paste(sub, (box_[idx, 0], box_[idx, 1]))
        else: # cls[idx] == 3:
            sub = Image.new('L', (w[idx], h[idx]), 255)
            mask3.paste(sub, (box_[idx, 0], box_[idx, 1]))
    mask = []
    mask.append(mask1)
    mask.append(mask2)
    mask.append(mask3)
    return mask

In [19]:
make_mask(1, cls_, box_)

AttributeError: 'int' object has no attribute 'size_w'

In [1]:
import cv2
import numpy as np
import os
import glob

# Path to your directory
image_dir = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images"

# Get list of .tif images
tif_images = glob.glob(os.path.join(image_dir, "*.tif"))

for image_path in tif_images:
    img = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)  # Load with original bit depth
    if img is None:
        print(f"Failed to load {image_path}")
        continue

    min_val = np.min(img)
    max_val = np.max(img)
    print(f"{image_path} -> Min: {min_val}, Max: {max_val}, Data Type: {img.dtype}")


/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images/10053000_2771910.tif -> Min: 0, Max: 255, Data Type: uint8
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images/10036489_2716875.tif -> Min: 0, Max: 255, Data Type: uint8
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images/10044745_2716875.tif -> Min: 0, Max: 255, Data Type: uint8
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images/10017227_2769158.tif -> Min: 0, Max: 255, Data Type: uint8
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images/10055752_2771910.tif -> Min: 0, Max: 255, Data Type: uint8
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/images/10039241_2777413.tif -> Min: 0, Max: 255, Data Type: uint8
/home/rishabh.mondal/Brick-Kilns-p

In [14]:
import os

# Define image and label paths
image_dir = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/domain_adaptation/MGUIT/results/synthetic/images"
label_dir = "/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/dhaka_grid_train/labels"

# Get all image and label filenames (without extensions)
image_files = {os.path.splitext(f)[0] for f in os.listdir(image_dir) if f.endswith(('.png', '.jpg', '.jpeg'))}
label_files = {os.path.splitext(f)[0] for f in os.listdir(label_dir) if f.endswith('.txt')}  # Assuming labels are .txt files

# Find matching and missing files
matching_files = image_files.intersection(label_files)
missing_labels = image_files - label_files
missing_images = label_files - image_files

# Print results
print(f"Total Images: {len(image_files)}")
print(f"Total Labels: {len(label_files)}")
print(f"Matching Files: {len(matching_files)}")
print(f"Images without Labels: {len(missing_labels)}")
print(f"Labels without Images: {len(missing_images)}")

# Optional: Print missing files
if missing_labels:
    print("\nImages without corresponding labels:")
    print("\n".join(missing_labels))

if missing_images:
    print("\nLabels without corresponding images:")
    print("\n".join(missing_images))


Total Images: 107
Total Labels: 135
Matching Files: 107
Images without Labels: 0
Labels without Images: 28

Labels without corresponding images:
10008972_2736137
10058503_2763654
10050248_2727882
10039241_2736137
10055752_2752647
10053000_2727882
10036489_2774661
10022731_2727882
10025483_2730634
10028234_2730634
10055752_2766406
10041993_2755399
10041993_2722378
10041993_2719627
10039241_2744392
10044745_2747144
10041993_2736137
10030986_2741640
10055752_2763654
10041993_2752647
10036489_2747144
10039241_2752647
10025483_2725130
10036489_2766406
10030986_2727882
10047496_2730634
10033738_2725130
10039241_2769158
