In [17]:
import numpy as np
from PIL import Image


In [29]:
text_path="/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/domain_adaptation/init_original_copy/label/sunny_train/sunny/sunny_1.txt"
a_path=np.loadtxt(text_path,dtype=str, delimiter=' ', skiprows=0, usecols=(0))
print(a_path)
print(a_path[0])

['/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/delhi_airshed/images/8558197_3353442.tif'
 '3' '0' '4' '1']
/home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/processed_data/delhi_airshed/images/8558197_3353442.tif


In [30]:
cls_ = np.loadtxt(text_path, dtype=int, delimiter=' ', skiprows=5, usecols=(0))
print(cls_)


1


In [31]:
# # text_path = "your_file.txt"

# with open(text_path, "r") as file:
#     lines = file.readlines()

# # Extract cls_ values, skipping non-numeric lines
# cls_ = []
# for line in lines[2:]:  # Start reading from the 3rd line (zero-based index)
#     parts = line.split()
#     if parts and parts[0].isdigit():  # Ensure the first element is a number
#         cls_.append(int(parts[0]))

# print(cls_)


In [32]:
box_ = np.loadtxt(text_path, dtype=float, delimiter=' ', skiprows=5, usecols=(1,2,3,4))
print(box_)


[2896. 1583. 3114. 1722.]


In [33]:
import numpy as np

# text_path = "your_file.txt"

# Read all lines
with open(text_path, "r") as file:
    lines = file.readlines()

# Skip non-numeric lines (First two lines contain non-relevant info)
numeric_lines = []
for line in lines[2:]:  # Skip first 2 lines (1.png and metadata)
    parts = line.strip().split()
    
    # Ensure the row has exactly 5 values (class_id + 4 box coordinates)
    if len(parts) == 5 and parts[0].isdigit():
        numeric_lines.append(" ".join(parts))  # Convert back to string

# Convert filtered lines to numpy array
if numeric_lines:
    from io import StringIO
    box_ = np.loadtxt(StringIO("\n".join(numeric_lines)), dtype=float, delimiter=" ", usecols=(1,2,3,4))
    print(box_)
else:
    print("No valid bounding box data found.")


[2896. 1583. 3114. 1722.]


In [34]:
# if box_.size == 4:
cls_ = np.expand_dims(cls_, axis=0)
box_ = np.expand_dims(box_, axis=0)
print(cls_)
print(box_)
print(cls_.shape)
print(box_.shape)

    # print(box_)
# mask_ = self.make_mask(cls_, box_)

[1]
[[2896. 1583. 3114. 1722.]]
(1,)
(1, 4)


In [38]:
box_ = np.round(box_ / 4) * 4
print(box_)
box_ = box_.astype('int')
print(box_)

[[2896. 1584. 3112. 1720.]]
[[2896 1584 3112 1720]]


In [39]:
print(box_.shape)
print(box_[:,2])

(1, 4)
[3112]


In [40]:
box_[:,0]

array([2896])

In [37]:
w = box_[:,2] - box_[:,0]
print(w)

[216]


In [18]:
def make_mask(self, cls, box):
    mask1 = Image.new('L', (self.size_w, self.size_h), 0)
    mask2 = Image.new('L', (self.size_w, self.size_h), 0)
    mask3 = Image.new('L', (self.size_w, self.size_h), 0)

    box_ = np.round(box / 4) * 4
    print("box_shape: ", box_.shape)
    box_ = box_.astype('int')

    w = box_[:,2] - box_[:,0]
    print("w shape: ", w.shape)

    h = box_[:,3] - box_[:,1]
    print("h shape: ", h.shape)
    print("clas size: ", cls.size)
    for idx in range(cls.size):
        if cls[idx] == 1:
            sub = Image.new('L', (w[idx], h[idx]), 255)
            mask1.paste(sub, (box_[idx, 0], box_[idx, 1]))
        elif cls[idx] == 2:
            sub = Image.new('L', (w[idx], h[idx]), 255)
            mask2.paste(sub, (box_[idx, 0], box_[idx, 1]))
        else: # cls[idx] == 3:
            sub = Image.new('L', (w[idx], h[idx]), 255)
            mask3.paste(sub, (box_[idx, 0], box_[idx, 1]))
    mask = []
    mask.append(mask1)
    mask.append(mask2)
    mask.append(mask3)
    return mask

In [19]:
make_mask(1, cls_, box_)

AttributeError: 'int' object has no attribute 'size_w'